[package]
name = "schoenberg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
clap-stdin = "0.6.0"
indexmap = "2.9.0"
midly = { version = "0.5.3", features = ["strict"] }

[dev-dependencies]
proptest = "1.6.0"
